services:
  kocky-app:
    build:
      context: .
      network: host
    container_name: kocky-app
    restart: always
    ports:
      - "6001:6001"
    env_file:
      - .env.production
    volumes:
      - ./db:/app/db
    command: sh -c "npx prisma migrate deploy && npx prisma db seed && node server.js"
    healthcheck:
      test: [ "CMD", "wget", "--no-verbose", "--tries=1", "--spider", "http://localhost:6001/api/auth/session" ]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s
